"""create 6 core tables

Revision ID: 3e439e7f00e3
Revises: 
Create Date: 2026-08-23 01:22:53.165092

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa



revision = '3e439e7f00e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_run',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('thread_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='run_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('checkpoint_ref', sa.String(length=256), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_run_task_id'), 'agent_run', ['task_id'], unique=False)
    op.create_table('artifact',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('object_key', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifact_task_id'), 'artifact', ['task_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_title', sa.Text(), nullable=True),
    sa.Column('locator', sa.String(length=256), nullable=True),
    sa.Column('content_ref', sa.Text(), nullable=True),
    sa.Column('claim_id', sa.String(length=64), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_claim_id'), 'evidence', ['claim_id'], unique=False)
    op.create_index(op.f('ix_evidence_task_id'), 'evidence', ['task_id'], unique=False)
    op.create_table('step',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('step_no', sa.Integer(), nullable=False),
    sa.Column('phase', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='step_status'), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=True),
    sa.Column('action_id', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('error_code', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_step_run_id'), 'step', ['run_id'], unique=False)
    op.create_table('task',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'QUEUED', 'RUNNING', 'PAUSED', 'FAILED', 'COMPLETED', 'CANCELLED', name='task_status'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('search_depth', sa.String(length=16), nullable=False),
    sa.Column('output_format', sa.String(length=16), nullable=False),
    sa.Column('budget_tokens', sa.Integer(), nullable=False),
    sa.Column('budget_seconds', sa.Integer(), nullable=False),
    sa.Column('budget_cost', sa.Float(), nullable=False),
    sa.Column('current_run_id', sa.String(length=64), nullable=True),
    sa.Column('lease_owner', sa.String(length=64), nullable=True),
    sa.Column('lease_expire_at', sa.DateTime(), nullable=True),
    sa.Column('result_ref', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_budget_usage',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('tool_calls', sa.Integer(), nullable=False),
    sa.Column('elapsed_ms', sa.BigInteger(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_budget_usage_task_id'), 'task_budget_usage', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_budget_usage_task_id'), table_name='task_budget_usage')
    op.drop_table('task_budget_usage')
    op.drop_table('task')
    op.drop_index(op.f('ix_step_run_id'), table_name='step')
    op.drop_table('step')
    op.drop_index(op.f('ix_evidence_task_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_claim_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_artifact_task_id'), table_name='artifact')
    op.drop_table('artifact')
    op.drop_index(op.f('ix_agent_run_task_id'), table_name='agent_run')
    op.drop_table('agent_run')
    # ### end Alembic commands ###
