"""remove lease fields from task

Revision ID: c1f29a4b9156
Revises: bbc2a7fc169a
Create Date: 2026-08-23 17:58:47.897528

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import mysql

revision = 'c1f29a4b9156'
down_revision = 'bbc2a7fc169a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'lease_owner')
    op.drop_column('task', 'lease_expire_at')
    op.alter_column('task_event', 'stream_id',
               existing_type=mysql.VARCHAR(length=64),
               comment='Redis Stream ID',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_event', 'stream_id',
               existing_type=mysql.VARCHAR(length=64),
               comment=None,
               existing_comment='Redis Stream ID',
               existing_nullable=False)
    op.add_column('task', sa.Column('lease_expire_at', mysql.DATETIME(), nullable=True))
    op.add_column('task', sa.Column('lease_owner', mysql.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
